version: 2
jobs:
  build:
    docker:
      - image: archlinux/base

    working_directory: ~/split_by_QR_code

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pacman -Syu --noconfirm
            pacman -S git file awk gcc --noconfirm
            pacman -S python python-pip --noconfirm
            pacman -S base-devel --noconfirm
            pacman -S zbar --noconfirm
            pacman -S ghostscript --noconfirm
            pacman -S python-wand --noconfirm
            echo '<policy domain="coder" rights="read|write" pattern="PDF" />' >> /etc/ImageMagick-7/policy.xml

            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov pytest pytest-cov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -vs

      -  run:
          name: upload coverage report
          command: |
            . venv/bin/activate
            pytest --cov=./
            codecov || echo "Error in uploading coverage reports to codecov.io."

      - store_artifacts:
          path: test-reports
          destination: test-reports

