# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:2.7.15-jessie

    working_directory: ~/pdf_split_by_QR_code

    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            apt-get update 
            aapt-get update && apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev libpng-dev build-essential
            apt-get install imagemagick ghostscript -y
            apt-get install libmagickwand-dev -y
            apt-get install zlib1g-dev -y
            apt-get install zbar-tools -y
            apt-get install libzbar-dev -y
            apt-get install ImageMagick -y
            apt-get install libpython-dev -y
            apt-get install python-pip -y
            
            pip install virtualenv 
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -vs

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
